<script setup>
import { inject, onMounted, ref } from "vue"; import { RouterLink } from "vue-router"; import PageHeader from "../components/PageHeader.vue"; import EmptyState from "../components/EmptyState.vue";
const services = inject("services"); const projects = ref([]); const name = ref(""); const editing = ref(); const error = ref("");
async function load() { projects.value = await services.projectService.listProjects(); }
async function save() { try { if (editing.value) await services.projectService.renameProject(editing.value.id, name.value); else await services.projectService.createProject({ name: name.value }); name.value = ""; editing.value = undefined; await load(); } catch (e) { error.value = e.message; } }
async function remove(project) { if (!window.confirm(`Excluir o projeto “${project.name}” e seus dados?`)) return; const environments = await services.projectService.listEnvironments(project.id); for (const environment of environments) { const elements = await services.projectService.listElements(environment.id); for (const element of elements) { for (const evaluation of await services.evaluationService.listEvaluations(element.id)) await services.repositories.evaluationRepository.delete(evaluation.id); await services.repositories.elementRepository.delete(element.id); } await services.repositories.environmentRepository.delete(environment.id); } await services.repositories.projectRepository.delete(project.id); await load(); }
function startEdit(project) { editing.value = project; name.value = project.name; }
onMounted(load);
</script>
<template><PageHeader eyebrow="Visão geral" title="Projetos" description="Acompanhe seus locais e avaliações."><template #action><button class="button" @click="editing = {}; name = ''">+ Novo projeto</button></template></PageHeader><form v-if="editing" class="form-card" @submit.prevent="save"><label class="field"><span>{{ editing.id ? 'Nome do projeto' : 'Novo projeto' }}</span><input v-model="name" required autofocus></label><p v-if="error" class="muted">{{ error }}</p><div class="form-actions"><button class="button button--ghost" type="button" @click="editing = undefined">Cancelar</button><button class="button">Salvar</button></div></form><div v-if="projects.length" class="card-list"><article v-for="project in projects" :key="project.id" class="card project-card"><RouterLink class="card__link" :to="`/projects/${project.id}`"><span class="card__icon">▦</span><div><h2>{{ project.name }}</h2><p>Atualizado em {{ new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium' }).format(new Date(project.updatedAt)) }}</p></div><span class="chevron">›</span></RouterLink><div class="card__menu"><button class="text-button" @click="startEdit(project)">Editar</button><button class="text-button text-button--danger" @click="remove(project)">Excluir</button></div></article></div><EmptyState v-else title="Comece por um projeto" text="Organize as avaliações de acessibilidade por obra ou local."><button class="button" @click="editing = {}; name = ''">+ Novo projeto</button></EmptyState></template>
