<script setup>
import { inject, onMounted, ref } from "vue"; import { RouterLink } from "vue-router"; import PageHeader from "../components/PageHeader.vue"; import EmptyState from "../components/EmptyState.vue";
const props = defineProps({ projectId: String }); const services = inject("services"); const project = ref(); const environments = ref([]); const name = ref(""); const editing = ref();
async function load() { project.value = await services.projectService.getProject(props.projectId); if (project.value) environments.value = await services.projectService.listEnvironments(props.projectId); }
async function save() { if (editing.value?.id) await services.projectService.renameEnvironment(editing.value.id, name.value); else await services.projectService.createEnvironment(props.projectId, { name: name.value }); editing.value = undefined; name.value = ""; await load(); }
async function remove(environment) { if (!window.confirm(`Excluir o ambiente “${environment.name}” e seus elementos?`)) return; for (const element of await services.projectService.listElements(environment.id)) { for (const evaluation of await services.evaluationService.listEvaluations(element.id)) await services.repositories.evaluationRepository.delete(evaluation.id); await services.repositories.elementRepository.delete(element.id); } await services.repositories.environmentRepository.delete(environment.id); await load(); }
onMounted(load);
</script>
<template><template v-if="project"><RouterLink class="back-link" to="/projects">‹ Projetos</RouterLink><PageHeader eyebrow="Projeto" :title="project.name" :description="`${environments.length} ambiente${environments.length === 1 ? '' : 's'} cadastrado${environments.length === 1 ? '' : 's'}.`"><template #action><button class="button" @click="editing = {}; name = ''">+ Novo ambiente</button></template></PageHeader><form v-if="editing" class="form-card" @submit.prevent="save"><label class="field"><span>Nome do ambiente</span><input v-model="name" required autofocus></label><div class="form-actions"><button class="button button--ghost" type="button" @click="editing = undefined">Cancelar</button><button class="button">Salvar</button></div></form><div v-if="environments.length" class="card-list"><article v-for="environment in environments" :key="environment.id" class="card"><RouterLink class="card__link" :to="`/projects/${project.id}/environments/${environment.id}`"><span class="card__icon">⌂</span><div><h2>{{ environment.name }}</h2><p>Ambiente do projeto</p></div><span class="chevron">›</span></RouterLink><div class="card__menu"><button class="text-button" @click="editing = environment; name = environment.name">Editar</button><button class="text-button text-button--danger" @click="remove(environment)">Excluir</button></div></article></div><EmptyState v-else title="Nenhum ambiente ainda" text="Adicione espaços como entrada, banheiro ou circulação."><button class="button" @click="editing = {}; name = ''">+ Novo ambiente</button></EmptyState></template><EmptyState v-else title="Projeto não encontrado" text="Ele pode ter sido removido."><RouterLink class="button" to="/projects">Voltar aos projetos</RouterLink></EmptyState></template>
